import math

EXPLORATION_PARAMETER = math.sqrt(2)
MONTE_CARLO_SIMULATIONS_COUNT = 500
MINIMAX_SEARCH_DEPTH = 2
DIRICHLET_NOISE_RATE = .25
DIRICHLET_NOISE_ALPHA_PARAMETER = 0.3
NUMBER_OF_SELF_PLAY_GAMES = 1
