import math

EXPLORATION_PARAMETER = math.sqrt(1)
MONTE_CARLO_SIMULATIONS_COUNT = 100
MINIMAX_SEARCH_DEPTH = 3
ALPHA_BETA_PRUNING_DEPTH = 2
DIRICHLET_NOISE_RATE = .3
DIRICHLET_NOISE_ALPHA_PARAMETER = 0.3
NUMBER_OF_SELF_PLAY_GAMES = 2
