import pygame

TEXT_FONT = "couriersansms"
TEXT_SIZE = 50

WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 1000

HIGHLIGHTED_SQUARES_COLOR = pygame.Color(0, 6, 64, 204)
UNMOVABLE_PIECES_COLOR = pygame.Color(255, 201, 51)
CHECKED_KING_COLOR = pygame.Color(255, 0, 0)

START_BUTTON_TOP_LEFT_X = 1150
START_BUTTON_TOP_LEFT_Y = 90
START_BUTTON_WIDTH = 400
START_BUTTON_HEIGHT = 100
START_BUTTON_TEXT = "START NEW GAME"
START_BUTTON_COLOR = pygame.Color(96, 96, 159)
START_BUTTON_TEXT_COLOR = pygame.Color(0, 0, 0)

EDITOR_BUTTON_TOP_LEFT_X = 1150
EDITOR_BUTTON_TOP_LEFT_Y = 210
EDITOR_BUTTON_WIDTH = 400
EDITOR_BUTTON_HEIGHT = 100
EDITOR_BUTTON_TEXT = "EDITOR"
EDITOR_BUTTON_COLOR = pygame.Color(96, 96, 159)
EDITOR_BUTTON_TEXT_COLOR = pygame.Color(0, 0, 0)

INPUT_BOX_TOP_LEFT_X = 200
INPUT_BOX_TOP_LEFT_Y = 150
INPUT_BOX_WIDTH = 600
INPUT_BOX_HEIGHT = 100
INPUT_BOX_COLOR = pygame.Color(96, 96, 159)
INPUT_BOX_TEXT_COLOR = pygame.Color(0, 0, 0)
INPUT_BOX_INACTIVE_COLOR = pygame.Color('lightskyblue3')
INPUT_BOX_ACTIVE_COLOR = pygame.Color('dodgerblue2')

INPUT_BOX_INTRO_TEXT_TOP_LEFT_X = 200
INPUT_BOX_INTRO_TEXT_TOP_LEFT_Y = 100
INPUT_BOX_INTRO_TEXT_WIDTH = 600
INPUT_BOX_INTRO_TEXT_HEIGHT = 50
INPUT_BOX_INTRO_TEXT_COLOR = pygame.Color(96, 96, 159)
INPUT_BOX_INTRO_TEXT_TEXT_COLOR = pygame.Color(0, 0, 0)

RESIGN_BUTTON_TOP_LEFT_X = 1150
RESIGN_BUTTON_TOP_LEFT_Y = 910
RESIGN_BUTTON_WIDTH = 400
RESIGN_BUTTON_HEIGHT = 80
RESIGN_BUTTON_TEXT = "RESIGN"
RESIGN_BUTTON_COLOR = pygame.Color(204, 96, 23)
RESIGN_BUTTON_TEXT_COLOR = pygame.Color(0, 0, 0)

DRAW_BUTTON_TOP_LEFT_X = 900
DRAW_BUTTON_TOP_LEFT_Y = 910
DRAW_BUTTON_WIDTH = 200
DRAW_BUTTON_HEIGHT = 80
DRAW_BUTTON_TEXT = "DRAW"
DRAW_BUTTON_COLOR = pygame.Color(188, 96, 23)
DRAW_BUTTON_TEXT_COLOR = pygame.Color(0, 0, 0)

RESTART_BUTTON_TEXT = "RESTART"
RESTART_BUTTON_COLOR = pygame.Color(128, 102, 153)

GAME_INFO_TOP_LEFT_X = 900
GAME_INFO_TOP_LEFT_Y = 250
GAME_INFO_WIDTH = 650
GAME_INFO_HEIGHT = 650
GAME_INFO_COLOR = pygame.Color(96, 96, 159)
GAME_INFO_TEXT_FONT = "couriersansms"
GAME_INFO_TEXT_SIZE = 30
GAME_INFO_TEXT_COLOR = pygame.Color(0, 0, 0)
GAME_INFO_LINE_OFFSET = 10
GAME_INFO_COLUMN_OFFSET = 10
GAME_INFO_LINE_INTERVAL = 40

CLEAR_SCREEN_COLOR = pygame.Color(255, 255, 255)

SQUARE_SIZE = 100

INPUT_BOX_OFFSET = 10
