from enum import Enum


class GameResult(Enum):
    WHITE_WINS_BY_CHECKMATE = 1
    BLACK_WINS_BY_CHECKMATE = 2
    DRAW_BY_STALEMATE = 3
    WHITE_WINS_BY_RESIGNATION = 4
    BLACK_WINS_BY_RESIGNATION = 5
    DRAW_BY_MOVE_REPEAT = 6
    DRAW_BY_MUTUAL_AGREEMENT = 7
    UNDEFINED = 8
    WHITE_WINS_ON_TIME = 9
    BLACK_WINS_ON_TIME = 10
